# locale                   : "en-US"

remote_theme             : "mmistakes/minimal-mistakes@4.15.1"
title                    : [Kanan Saikai's webpage]
# title_separator          : "-"
# name                     : "Kanan Saikai"
# description              : "Personal website"

# # Site Author
# author:
#   name             : "Kanan Saikai"
#   avatar           : "bio_photo.jpg" # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
#   bio              : "a nematode (and cat) lover"
#   location         : "Madison, WI"
#   email            :
#   uri              : 
#   home             : # null (default), "absolute or relative url to link to author home"
#   facebook         :
#   github           : "ksaikai"
#   gitlab           :
#   instagram        :
#   linkedin         :  # "john-doe-12345678" (the last part of your profile url, e.g. https://www.linkedin.com/in/john-doe-12345678)
#   stackoverflow    : # "123456/username" (the last part of your profile url, e.g. https://stackoverflow.com/users/123456/username)
#   steam            : # "steamId" (the last part of your profile url, e.g. https://steamcommunity.com/id/steamId/)
#   twitter          : 
#   vine             :
#   youtube          : # "https://youtube.com/c/MichaelRoseDesign"
  
  
# # Defaults
# defaults:
#   # _posts
#   - scope:
#       path: ""
#       type: posts
#     values:
#       layout: single
#       author_profile: true
#       read_time: true
#       comments: # true
#       share: true
#       related: true

#   # _pages
#   - scope:
#       path: ""
#       type: pages
#     values:
#       layout: single
#       author_profile: true
